# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mongo_failover"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Zachary Kloepping"]
  s.date = "2013-10-09"
  s.description = "Patch mongo ruby driver to handle failover events via retry"
  s.email = "kloeppingzd@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/mongo_failover.rb",
    "test/failover_test.rb",
    "test/helper.rb"
  ]
  s.homepage = "http://github.com/moxiespaces/mongo_failover"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Patch mongo ruby driver to handle failover events"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongo>, [">= 1.8.2"])
      s.add_runtime_dependency(%q<bson_ext>, [">= 1.8.2"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.2.13"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<fury>, [">= 0"])
    else
      s.add_dependency(%q<mongo>, [">= 1.8.2"])
      s.add_dependency(%q<bson_ext>, [">= 1.8.2"])
      s.add_dependency(%q<activesupport>, [">= 3.2.13"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<fury>, [">= 0"])
    end
  else
    s.add_dependency(%q<mongo>, [">= 1.8.2"])
    s.add_dependency(%q<bson_ext>, [">= 1.8.2"])
    s.add_dependency(%q<activesupport>, [">= 3.2.13"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<fury>, [">= 0"])
  end
end

